- name: removes wireshark
  become: yes
  hosts: all_dev
  tasks:
    - name: remove whireshark (RedHat)
      yum: name=wireshark state=removed
      when: ansible_facts.distribution == "RedHat"
    - name: remove whireshark (Ubuntu)
      apt:
        name: wireshark
        state: absent
        purge: yes
        autoclean: yes
      when: ansible_facts.distribution == "Ubuntu"