#---
#- name: run on all hosts
#  import_playbook: ../static-assignments/common.yml

---
- name: Include dynamic variables
  hosts: uat
  pre_tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
  tasks:
    - debug: 
        msg: "need lb: {{ enable_apache_lb }}"
    - name: Loadblalancers assignment
      include_tasks: ../static-assignments/loadbalancers.yml
      vars:
        load_balancer_is_required: "{{ load_balancer_is_required }}"
        enable_apache_lb: "{{ enable_apache_lb }}"
        enable_nginx_lb: "{{ enable_nginx_lb }}"
      when: load_balancer_is_required


#- name: Webserver assignments
#  import_playbook: ../static-assignments/uat-webservers.yml