---
- hosts: all
- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml
  include_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: uat_webservers
- name: Webserver assignments
  import_playbook: ../static-assignments/uat-webservers.yml

- hosts: lb
- name: Loadblalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required