---
- name: Include dynamic variables
  hosts: all
  tasks:
    - import_playbook: ../static-assignments/common.yml
    - include_playbook: ../dynamic-assignments/env-vars.yml

- name: Webserver assignments
  hosts: uat_webservers
  tasks:
    - import_playbook: ../static-assignments/uat-webservers.yml