#---
#- name: run on all hosts
#  import_playbook: ../static-assignments/common.yml

---
- name: Include dynamic variables
  hosts: uat-webservers
  pre_tasks: 
    - include_tasks: ../dynamic-assignments/env-vars.yml
  tasks:
    - debug: 
        msg: "need lb: {{ load_balancer_is_required }}"
    - name: Loadblalancers assignment
      include_tasks: ../static-assignments/loadbalancers.yml
      when: load_balancer_is_required


#- name: Webserver assignments
#  import_playbook: ../static-assignments/uat-webservers.yml