---
- name: run on all hosts
  import_playbook: ../static-assignments/common.yml

- name: Include dynamic variables
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: uat_webservers
- name: Webserver assignments
  import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadblalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required